triton-inference-server/tensorrt_backend

- src/tensorrt.cc
The cyclic order for the instances will be handled by the RateLimiter. See the supporting core side changes here: https://github.com/triton-inference-server/server/pull/3078
Remaining in the backend:
1. Perf regression in TRT inference (Larger compute input times compared to our core TRT implementation)
1. DLA support
2. Extra logging
3. Clean CI run
> Enable asynchronous operation in the backend

- src/tensorrt.cc
This prevents the HtoD overwrites which causes inaccurate values.
> Fix the extra context index in the queue

- README.md
- src/tensorrt.cc
TRT backend is an example of explicitly enable request input coalescent if requested via backend config. TRT backend is the only backend that require this optimization and will only apply the same change to other backends if requested.
> Initialize BackendInputCollector with coalesce input argument

- src/tensorrt.cc
This fixes: 
> autofill failed for model 'plan_zero_1_float32': configuration specified max-batch 8 but TensorRT engine only supports max-batch 0
> Allow auto-complete to work alongside ragged batch inputs

- src/tensorrt.cc
According to the docs: 
> For an engine built from an [INetworkDefinition](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_network_definition.html) without an implicit batch dimension, this will always return 1.
Source:
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_cuda_engine.html#a5c2185618a25cc94b588b3318be3b27d
This fixes `nobatch_*` model tests in likes of `L0_trt_reformat_free`.
@nv-kmcgill53  See how a lack of `config_batch_hint` in presence of non-zero `tensors_with_config_shape_cnt`  is treated as a case for batching being disabled.
> Handle implicit batch dimension for non batching models

- src/tensorrt.cc
We should be adding to the list of sequence states in the payload instead of overriding it. This fixes implicit state for TRT models that have more than one implicit state.
> Fix implicit state for models that have more than one state

- src/tensorrt.cc
Autocomplete  now sets the dynamic_batcher when no scheduler is set and max_batch_size >1. This behavior is identical to the tensorflow and onnxruntime backends.
> Autocomplete sets dynamic batcher when none set

- src/tensorrt.cc
- src/tensorrt_model.cc
- src/tensorrt_model.h
Uses the utility added by PR: https://github.com/triton-inference-server/backend/pull/64/files
After the update, we run the parsing on entire config just to be more future-proof in case backends add more auto-complete functionalities.
> Use the SetModelConfig backend utility and parse the config again

- src/tensorrt.cc
Autocomplete attempts to load a model before model instances are created in core which causes a cuda runtime exception when no device is present. This PR fixes this problem by skipping autocomplete if there are no KIND_GPU instance groups in the model config. Triton core resolves the instance group kinds before the BackendModelInit function is called so we can rely on the current model config to give accurate information.
> Fix L0_infer--cpu

- src/tensorrt.cc
We need to handle the returned `TRITONSERVER_ErrorNew` object properly to prevent memory leak from unhandled `TRITONSERVER_ErrorNew`.
I noticed in our repos, there are some APIs that are not being handled for this properly, i.e. missing `RETURN_IF_ERROR` for API calls. Created a follow-up ticket DLIS-4007 for checking if we handle error return for all the TritonJson API calls.
Related PRs:
server: https://github.com/triton-inference-server/server/pull/4693
common: https://github.com/triton-inference-server/common/pull/67
backend: https://github.com/triton-inference-server/backend/pull/67
> Add RETURN_IF_ERROR for allow_ragged_batch variable

- src/tensorrt.cc
Dlclose is [not listed by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_04_03) as a safe function to call during signal handling, and thereby, "the behavior is undefined... if the signal handler calls any function defined in this standard other than one of the functions listed."
This ticket removes dlclose from the backend unloading. The plugin files should be closed and cleaned when the program/server shuts down, which is the only time backends are unloaded currently. This prevents potential race conditions that could cause the server to segfault (or have other unexpected behavior, e.g. deadlocking) during backend unloading.
> Remove Dlclosing of Plugins on Shutdown

- src/model_state.h
The memory leak happened because the object in the derived class was not cleaned up. Added virtual destructor to the base class so that the destructor of derived class would be called.
> Add virtual destructor to the base class

- src/instance_state.cc
- src/instance_state.h
Old:
```
Avg request latency: 3160 usec (overhead 48 usec + queue 127 usec + compute input 222 usec + compute infer 2705 usec + compute output 56 usec)
```
New:
```
Avg request latency: 3205 usec (overhead 59 usec + queue 153 usec + compute input 162 usec + compute infer 2665 usec + compute output 165 usec)
```
The actual copies for the model take ~100us for both inputs and outputs. I think the new measurements are closer to what is observed in the nsight trace for this model.
> Implement event timing using cudaEventElapsed

- src/instance_state.cc
- src/instance_state.h
When using eager_batching, the issue thread can override compute_input_start event. This may happen before a ProcessResponse thread has had a chance to retrieve the timestamp from the event. This happens because the ProcessResponse releases the semaphore for issue thread to proceed before retrieving the timestamp. Having 2 set of events help in normal scenario. But for eager batching we would need an additional set of events.
Otherwise we would run into errors like:
```
I0227 22:07:23.460482 275649 instance_state.cc:1243] elapsed time failed.: device not ready
```
> Remove input buffer reset. Increase the cuda event set

- src/instance_state.cc
- src/loader.cc
- src/loader.h
- src/logging.cc
- src/logging.h
- src/model_state.cc
- src/model_state.h
- src/tensorrt.cc
Currently, the TensorRT error message are only printed to Triton error log, but not cannot be propagated back to the Triton client making the request. The PR adds the capability to store the last TensorRT error message from the model that generates the error, and propagates the error back to the Triton client, as a supplement for existing error messages that lack some context (i.e. "unable to create TensorRT runtime" and "unable to create TensorRT context")
Related PR: https://github.com/triton-inference-server/server/pull/5651
Closes triton-inference-server/server/issues/5304
> Add more context to TensorRT error message

- src/instance_state.cc
The utility function expects a model name, but caller supplied model instance name instead. This PR fixes this problem. See the first parameter of `CompareDimsSupported()`.
The ultimate goal of this PR is to fix L0_model_config, which the model instance name no longer matches the model name when `count = 1` after merging https://github.com/triton-inference-server/core/pull/231.
> Fix printing instance name when model name is expected

- src/instance_state.cc
We have encountered a segmentation fault in the code at [tensorrt_backend/src/instance_state.cc#L4019](https://github.com/triton-inference-server/tensorrt_backend/blob/main/src/instance_state.cc#L4019) on using CUDA graphs. This is due to the `next_buffer_binding_set_` index going out of bounds.
`next_buffer_binding_set_` is updated at [tensorrt_backend/src/instance_state.cc#L3688](https://github.com/triton-inference-server/tensorrt_backend/blob/main/src/instance_state.cc#L3688) and uses `EVENT_SET_COUNT`.
This issue started occurring after increasing the `EVENT_SET_COUNT` from 2 to 3 in the [pull request](https://github.com/triton-inference-server/tensorrt_backend/pull/66/files#diff-d846a3687afe3645a6f657179a41075781a5f16cacc29ea7d1c8d474e0074f37R45) r23.03 release.
Restricting …
> Fix Segmentation Fault During TRT Model Initialization with CUDA Graphs Enabled

- CMakeLists.txt
- src_trt8/filesystem.cc
- src_trt8/filesystem.h
- src_trt8/instance_state.cc
- src_trt8/instance_state.h
- src_trt8/io_binding_info.cc
- src_trt8/io_binding_info.h
- src_trt8/libtriton_tensorrt.ldscript
- src_trt8/loader.cc
- src_trt8/loader.h
- src_trt8/logging.cc
- src_trt8/logging.h
- src_trt8/model_state.cc
- src_trt8/model_state.h
- src_trt8/output_allocator.cc
- src_trt8/output_allocator.h
- src_trt8/semaphore.h
- src_trt8/shared_library.cc
- src_trt8/shared_library.h
- src_trt8/tensorrt.cc
- src_trt8/tensorrt_model.cc
- src_trt8/tensorrt_model.h
- src_trt8/tensorrt_model_instance.cc
- src_trt8/tensorrt_model_instance.h
- src_trt8/tensorrt_utils.cc
- src_trt8/tensorrt_utils.h
This should allow building on iGPU which is coming with TRT 8.
The src_trt8 is just the current backend source r24.05  without @pskiran1 's changes for building on TRT 10.
> Include source for building on TRT 8

- CMakeLists.txt
Resolves this build issue on Windows:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVINFER_LIBRARY
linked by target "triton-tensorrt-backend" in directory C:/tmp/tritonbuild/tensorrt
NVINFER_PLUGIN_LIBRARY
linked by target "triton-tensorrt-backend" in directory C:/tmp/tritonbuild/tensorrt
-- Generating done (0.2s)
CMake Warning:
Manually-specified variables were not used by the project:
TRITON_ENABLE_METRICS
TRT_VERSION
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
> fix: Add _10 version suffix to NVINFER_LIBRARY and NVINFER_PLUGIN_LIBRARY for TRT 10 Windows Build

- CMakeLists.txt
`shape_tensor.cc` and `shape_tensor.h` need to be included only for TRT v10 and above.
> Fix tensorrt backend igpu build

- src/instance_state.cc
- src/instance_state.h
- src/model_state.cc
- src/model_state.h
- src/tensorrt_utils.cc
- src/tensorrt_utils.h
- Added support for the `is_non_linear_format_io` flag in the model configuration to identify whether input/output tensors use a non-linear IO format.
- Modified the auto-complete configuration to correctly initialize the `is_shape_tensor` and `is_non_linear_format_io` flags.
- For tensors using the non-linear IO format (reformat-free tensors), the backend now validates the input byte size.
> Fix shape and reformat free tensor handling in the input byte size check

- CMakeLists.txt
**Goal:** Support the TensorRT Backend on RHEL8 systems. Only change necessary here was assistance to find the `libnvinfer*` libraries.
Server Changes: https://github.com/triton-inference-server/server/pull/7568
PyTorch Backend: https://github.com/triton-inference-server/pytorch_backend/pull/137
TensorFlow: https://github.com/triton-inference-server/tensorflow_backend/pull/105
ORT Backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/266
> build: RHEL8 TensorRT Backend

- CMakeLists.txt
* skip warning errors
* Revert "skip warning errors"
This reverts commit 97456d081b1d6ed0445d6e0a52c85142e8549918.
* disable maybe-uninitialize warning errors
* remove werror
> Build Updates for Ubuntu24.04 (#102)

- README.md
- src/instance_state.cc
- src/model_state.cc
- src/model_state.h
The changes in the PR support 2 main items:
1. the GPU memory is allocated based on the selected TensorRT profile and not based on the profile that consumes max memory even when it's not selected.
2. Avoid the creation of profile 0 execution context if it's required.
> feat: Support for allocating GPU memory based on the selected profile

- src/instance_state.cc
- src/model_state.cc
- src/shape_tensor.cc
- src/shape_tensor.h
TRT 10.11.0 Release note: https://docs.nvidia.com/deeplearning/tensorrt/10.11.0/getting-started/release-notes.html
> Deprecated the int32_t version of the profile shape API, including: setShapeValues, getShapeValues, and getProfileTensorValues. We recommend you use version 2 instead.
Segfault is caused by `getProfileTensorValues` returns unexpected nullptr for shape tensors ([relevant lines](https://github.com/triton-inference-server/tensorrt_backend/blob/9d7ba1d5fa76ed958db9430b1dc435d485505a97/src/model_state.cc#L711-L714)). Updating `getProfileTensorValues` to `getProfileTensorValuesV2` fixed the segfault.
> ci: Fix shape tensor segfault

- src/shape_tensor.cc
- src/shape_tensor.h
Fix patch for https://github.com/triton-inference-server/tensorrt_backend/pull/112
Fixes
- L0_trt_shape_tensors_shm--TensorRT
- L0_trt_shape_tensors--TensorRT
Pipeline: 30288199
> ci: Update SetDataFromShapeValues implementation after changing shape_values type
